shellEmulator: true
trustPolicy: no-downgrade

packages:
  - test/basic-app
  - test/production-app
  - test/cloudflare-app

catalog:
  '@antfu/eslint-config': ^8.1.1
  '@cloudflare/workers-types': ^4.20260409.1
  '@types/node': ^24.12.2
  bumpp: ^11.0.1
  cookie-es: ^2.0.1
  dotenv: ^17.4.1
  eslint: ^10.2.0
  eslint-flat-config-utils: ^3.1.0
  get-port-please: ^3.2.0
  nitro: npm:nitro-nightly@latest
  ofetch: ^2.0.0-alpha.3
  tsdown: ^0.21.7
  typescript: ^6.0.2
  unbuild: ^3.6.1
  vite: ^8.0.8
  vitest: ^4.1.4
  wrangler: ^4.81.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - workerd
