shellEmulator: true
trustPolicy: no-downgrade

packages:
  - test/basic-app
  - test/production-app
  - test/cloudflare-app
  - test/vite-app

catalog:
  '@antfu/eslint-config': ^8.2.0
  '@cloudflare/workers-types': ^4.20260501.1
  '@types/node': ^24.12.2
  bumpp: ^11.0.1
  cookie-es: ^3.1.1
  dotenv: ^17.4.2
  eslint: ^10.2.1
  eslint-flat-config-utils: ^3.2.0
  nitro: ^3.0.260429-beta
  ofetch: ^2.0.0-alpha.3
  tsdown: ^0.21.10
  typescript: ^6.0.3
  unbuild: ^3.6.1
  vite: ^8.0.10
  vitest: ^4.1.5
  wrangler: ^4.87.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - workerd
